import type { Metadata } from "next";
import { Assistant } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import Container from "@/components/container";

const roboto = Assistant({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Compound Interest Calculator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} text-gray-500 dark:bg-slate-900 dark:text-gray-300 bg-gray-50`}
      >
        <Container>
          <Header />
          {children}
        </Container>
      </body>
    </html>
  );
}
